name: data100
channels:
- defaults
dependencies:
- asn1crypto=0.23.0
- bleach=2.1.1
- ca-certificates=2017.08.26
- certifi=2017.11.5
- cffi=1.11.2
- chardet=3.0.4
- cryptography=2.1.4
- cycler=0.10.0
- dbus=1.10.22
- decorator=4.1.2
- entrypoints=0.2.3
- expat=2.2.5
- freetype=2.8
- gettext=0.19.8.1
- glib=2.53.6
- html5lib=1.0.1
- icu=58.2
- idna=2.6
- intel-openmp=2018.0.0
- ipykernel=4.7.0
- ipython=6.2.1
- ipython_genutils=0.2.0
- ipywidgets=7.0.5
- jedi=0.11.0
- jinja2=2.10
- jpeg=9b
- jsonschema=2.6.0
- jupyter=1.0.0
- jupyter_client=5.1.0
- jupyter_console=5.2.0
- jupyter_core=4.4.0
- libedit=3.1
- libffi=3.2.1
- libiconv=1.15
- libpng=1.6.32
- libprotobuf=3.4.1
- libsodium=1.0.15
- libxml2=2.9.4
- libxslt=1.1.29
- lxml=4.1.1
- markupsafe=1.0
- matplotlib=2.1.1
- mistune=0.8.1
- mkl=2018.0.1
- nbconvert=5.3.1
- nbformat=4.4.0
- ncurses=6.0
- networkx=2.0
- notebook=5.2.2
- numpy=1.12.1
- openssl=1.0.2n
- pandas=0.21.1
- pandoc=1.19.2.1
- pandocfilters=1.4.2
- parso=0.1.1
- patsy=0.4.1
- pcre=8.41
- pexpect=4.3.0
- pickleshare=0.7.4
- pip=9.0.1
- plotly=2.2.2
- prompt_toolkit=1.0.15
- protobuf=3.4.1
- ptyprocess=0.5.2
- pycparser=2.18
- pygments=2.2.0
- pyopenssl=17.5.0
- pyparsing=2.2.0
- pyqt=5.6.0
- pysocks=1.6.7
- python=3.6.3
- python-dateutil=2.6.1
- pytz=2017.3
- pyzmq=16.0.3
- qt=5.6.2
- qtconsole=4.3.1
- readline=7.0
- requests=2.18.4
- scikit-learn=0.19.1
- scipy=1.0.0
- seaborn=0.8.1
- setuptools=36.5.0
- simplegeneric=0.8.1
- sip=4.18.1
- six=1.11.0
- sqlite=3.20.1
- statsmodels=0.8.0
- tensorflow=1.1.0=np112py36_0
- terminado=0.6
- testpath=0.3.1
- tk=8.6.7
- toolz=0.8.2
- tornado=4.5.2
- traitlets=4.3.2
- urllib3=1.22
- wcwidth=0.1.7
- webencodings=0.5.1
- werkzeug=0.12.2
- wheel=0.30.0
- widgetsnbextension=3.0.8
- xz=5.2.3
- zeromq=4.2.2
- zlib=1.2.11
- pip:
  - colorlover==0.2.1
  - cufflinks==0.12.1
  - oauthlib==2.0.6
  - requests-oauthlib==0.8.0
  - tweepy==3.5.0
